export const GET_SELECTED_FRIEND_SUCCESS = "GET_SELECTED_FRIEND_SUCCESS"
export const GET_SHARED_MEDIA_SUCCESS = "GET_SHARED_MEDIA_SUCCESS"
export const UPDATE_SHARED_MEDIA_SUCCESS = "UPDATE_SHARED_MEDIA_SUCCESS"